#!/bin/bash
#
# This script calls many other scripts to configure a fresh
# install of Ubuntu
# 
# Warning: ensure Software Update is done with its 
# 'first boot' run before starting this script
#
# Download this script directly from GitHub:
# $ wget https://bit.ly/elt2jvZ
#
# Overview of events:
# 
# * create directory for git
# * install git
# * clone git repos
# * link dotfiles to git repo
#
# Run as normal user NOT root
#
# ensure `apt` is NOT running:
#
# $ ps aux | grep apt | grep root  # note process ID
# $ sudo kill XXXX
#
# get all of the scripts:
sudo apt install -y git &&\
mkdir $HOME/git-files &&\
cd $HOME/git-files &&\
git clone https://github.com/ersanchez/bin.git &&\
git clone https://github.com/ersanchez/dotfiles.git &&\
$HOME/git-files/bin/cfgdotfiles
