#!/bin/bash
#
# link dotfiles to git repo
cd $HOME/git-files/

removeold() {
  rm -rf .bash_logout
  rm -rf .bashrc
  rm -rf .profile
}

linknew() {
  ln -sb $HOME/git-files/dotfiles/.abcde $HOME/
  ln -sb $HOME/git-files/dotfiles/.bash_logout $HOME/
  ln -sb $HOME/git-files/dotfiles/.bash_profile $HOME/
  ln -sb $HOME/git-files/dotfiles/.bashrc $HOME/
  ln -sb $HOME/git-files/dotfiles/.bashrc_custo $HOME/
  ln -sb $HOME/git-files/dotfiles/.gitconfig $HOME/
  ln -sb $HOME/git-files/dotfiles/.gitignore_global $HOME/
  ln -sb $HOME/git-files/dotfiles/.profile $HOME/
  ln -sb $HOME/git-files/dotfiles/.tmux.conf $HOME/
  ln -sb $HOME/git-files/dotfiles/.vim $HOME/
  ln -sb $HOME/git-files/dotfiles/.vimrc $HOME/
}

removeold &&\
linknew
